hostname: 10.89.243.49
username: johnhes@ACELAB.local
password: Winter21!
su_password: password123
ansible_user: johnhession
ansible_ssh_pass: password123
ansible_become: True
ansible_become_pass: password123
ansible_host_key_checking: False


